name: Generate artifacts on PR
#
# Update artifacts on PR if developers is a part of Armbian board maintainers team
#

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: pipeline-pr-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:

  Check:

    name: "Permission to run compilation"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: Linux
    outputs:
      member: ${{ steps.checkUserMember.outputs.isTeamMember }}
    steps:

      -  uses: tspascoal/get-user-teams-membership@v2
         id: checkUserMember
         with:
           username: ${{ github.actor }}
           organization: armbian
           team: "Board Maintainers"
           GITHUB_TOKEN: ${{ secrets.ORG_MEMBERS }}

  Compile:

    needs: Check
    name: "Update artifacts"
    if: ${{ github.repository_owner == 'Armbian' && needs.Check.outputs.member == 'true' }}
    uses: armbian/os/.github/workflows/complete-artifact-matrix-all.yml@main
    secrets:
      ORG_MEMBERS: ${{ secrets.ORG_MEMBERS }}
    with:
      extraParamsAllBuilds: "UPLOAD_TO_OCI_ONLY=no"
      ref: ${{ github.event.pull_request.head.sha }}
